// Package handler is the Vercel serverless entry point.
// Vercel looks for an exported http.HandlerFunc named Handler in api/*.go.
package handler

import (
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"

	"happywork.com/internal/bitbucket"
	"happywork.com/internal/config"
	"happywork.com/internal/gemini"
	"happywork.com/internal/webhook"
)

// Handler is the single entry point Vercel invokes for every request to
// /api/webhook (mapped in vercel.json).
func Handler(w http.ResponseWriter, r *http.Request) {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))

	if r.Method == http.MethodGet {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintln(w, "ok")
		return
	}

	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	cfg, err := config.Load()
	if err != nil {
		logger.Error("loading config", "error", err)
		http.Error(w, "server misconfiguration", http.StatusInternalServerError)
		return
	}

	geminiClient := gemini.New(cfg.GeminiAPIKey, cfg.GeminiModel)
	bbClient := bitbucket.New(
		cfg.BitbucketBaseURL,
		cfg.BitbucketWorkspace,
		cfg.BitbucketAPIKey,
	)

	event, err := webhook.Parse(r, cfg.JiraWebhookSecret)
	if err != nil {
		logger.Warn("invalid webhook", "error", err)
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}

	if !webhook.IsTransitionTo(event, cfg.JiraTriggerStatus) {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	issueKey := event.Issue.Key
	log := logger.With("issue", issueKey)
	log.Info("issue transitioned – starting work")

	repoSlug := os.Getenv("BITBUCKET_REPO_SLUG")
	if repoSlug == "" {
		repoSlug = strings.ToLower(event.Issue.Fields.Project.Key)
	}

	issueCtx := gemini.IssueContext{
		Key:         issueKey,
		Summary:     event.Issue.Fields.Summary,
		Description: event.Issue.Fields.Description,
		IssueType:   event.Issue.Fields.IssueType.Name,
		ProjectKey:  event.Issue.Fields.Project.Key,
		RepoSlug:    repoSlug,
	}

	changes, err := geminiClient.GenerateChanges(issueCtx)
	if err != nil {
		log.Error("gemini failed", "error", err)
		http.Error(w, "upstream error", http.StatusBadGateway)
		return
	}
	log.Info("gemini produced changes", "files", len(changes))

	defaultBranch, err := bbClient.DefaultBranch(repoSlug)
	if err != nil {
		log.Error("fetching default branch", "error", err)
		http.Error(w, "bitbucket error", http.StatusBadGateway)
		return
	}

	featureBranch := "happy-work/" + strings.ToLower(issueKey)
	if err := bbClient.CreateBranch(repoSlug, featureBranch, defaultBranch); err != nil {
		log.Error("creating branch", "error", err)
		http.Error(w, "bitbucket error", http.StatusBadGateway)
		return
	}

	for _, change := range changes {
		commitMsg := fmt.Sprintf("[%s] %s", issueKey, change.Message)
		if err := bbClient.CommitFile(repoSlug, featureBranch, change.Path, change.Content, commitMsg); err != nil {
			log.Error("committing file", "path", change.Path, "error", err)
			http.Error(w, "bitbucket error", http.StatusBadGateway)
			return
		}
		log.Info("committed file", "path", change.Path)
	}

	prTitle := fmt.Sprintf("[%s] %s", issueKey, event.Issue.Fields.Summary)
	prDescription := fmt.Sprintf(
		"Automated PR generated by happy-work for Jira issue [%s].\n\n**Summary:** %s\n\n**Description:**\n%s",
		issueKey,
		event.Issue.Fields.Summary,
		event.Issue.Fields.Description,
	)
	prURL, err := bbClient.OpenPR(repoSlug, prTitle, prDescription, featureBranch, defaultBranch)
	if err != nil {
		log.Error("opening PR", "error", err)
		http.Error(w, "bitbucket error", http.StatusBadGateway)
		return
	}

	log.Info("PR opened", "url", prURL)
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, `{"pr_url":"%s"}`, prURL)
}
